--- 
engines: 
  brakeman: 
    enabled: true
  csslint: 
    enabled: true
  duplication: 
    config: ~
    enabled: true
    languages: 
      - javascript
  eslint: 
    enabled: true
  rubocop: 
    enabled: true
exclude_paths: 
  - web/panel/js/jquery-ui
  - web/panel/js/flot
  - web/panel/js/ion-sound
ratings: 
  paths: 
    - app/**
    - lib/**
    - "**.rb"
    - "**.go"