--- 
engines: 
  csslint: 
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
  eslint: 
    enabled: true
ratings:
  paths:
      - "web/"
exclude_paths: 
  - "web/panel/js/jquery"
  - "web/panel/js/jquery-ui"
