//Configuration for Control Panel
//Automatically Generated by PhantomBot at Startup
//Do NOT Modify! Overwritten when PhantomBot is restarted!
var panelSettings = {
    panelPort   : 9004,
    channelName : "lindgrenmax",
    auth        : "AoEzWYb9UlYcReGycMV8OITqfOO54E",
    http        : "http://"
};

function getPanelPort() { return panelSettings.panelPort; }
function getChannelName() { return panelSettings.channelName; }
function getAuth() { return panelSettings.auth; }
function getProtocol() { return panelSettings.http; }
